using DoenaSoft.ToolBox.Generics;

namespace DoenaSoft.FolderList.Xml;

/// <summary>
/// Reads files generated by this library.
/// </summary>
public static class MetaReader
{
    /// <summary>
    /// Reads the given file and returns the top-level items.
    /// </summary>
    /// <param name="fileName">the file name</param>
    /// <returns>the top-level items</returns>
    public static SubItem[] Read(string fileName)
    {
        var doc = XsltSerializer<FolderDocument>.Deserialize(fileName);

        return doc.RootItem;
    }
}