using System.Xml;
using DoenaSoft.ToolBox.Generics;

namespace DoenaSoft.FolderList.Xml;

/// <summary>
/// Reads files generated by this library.
/// </summary>
public static class Reader
{
    /// <summary>
    /// Reads the given file and returns the top-level items.
    /// </summary>
    /// <param name="fileName">the file name</param>
    /// <returns>the top-level items</returns>
    public static SubItem[] Read(string fileName)
    {
        using var stream = new FileStream(fileName, FileMode.Open, FileAccess.Read, FileShare.Read);

        using var xmlReader = new XmlTextReader(stream);

        var settings = new XmlReaderSettings()
        {
            DtdProcessing = DtdProcessing.Parse,
        };

        var doc = XmlSerializer<FolderDocument>.Deserialize(xmlReader);

        return doc.RootItem;
    }
}